---
- name: Restart nomad
  ansible.builtin.systemd:
    name: nomad.service
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
